name: Terraform CI Pipeline

on:
  workflow_dispatch:
    # inputs:
    #   aws_region:
    #     description: "AWS Region for the S3 bucket"
    #     required: true
    #     default: "us-east-1"
    #   bucket_name:
    #     description: "Name of the S3 bucket"
    #     required: true

jobs:
  terraform-ci:
    runs-on: ubuntu-latest
    env:
      TF_LOG: DEBUG  # Enable detailed Terraform logging
      ACTIONS_RUNNER_DEBUG: "true"  # Enable runner debug logging
      ACTIONS_STEP_DEBUG: "true"  # Enable step debug logging
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      # Step 1: Checkout repository code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TFC_API_TOKEN }}

      # Step 3: Initialize Terraform
      - name: Initialize Terraform
        run: terraform init

      # Step 4: Plan Terraform Changes
      - name: Terraform Plan
        # env:
        #   TF_VAR_aws_region: ${{ github.event.inputs.aws_region }}
        #   TF_VAR_bucket_name: ${{ github.event.inputs.bucket_name }}
        run: terraform plan

      # Optional Step: Trigger Terraform Cloud Apply
      - name: Trigger Terraform Cloud Apply
        env:
          TFC_API_TOKEN: ${{ secrets.TFC_API_TOKEN }}
        run: |
          curl --header "Authorization: Bearer $TFC_API_TOKEN" \
               --header "Content-Type: application/vnd.api+json" \
               --data '{
                   "data": {
                       "attributes": {
                           "is-destroy": false,
                           "message": "Triggered by GitHub Actions"
                       },
                       "type": "runs",
                       "relationships": {
                           "workspace": {
                               "data": {
                                   "type": "workspaces",
                                   "id": "<workspace-id>"
                               }
                           }
                       }
                   }
               }' \
               --request POST \
               "https://app.terraform.io/api/v2/runs"
